/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package misFormularios;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author USER
 */
public class Mantenedor extends javax.swing.JFrame {

    FondoPanel fondo = new FondoPanel();

    public Mantenedor() {
        
        this.setContentPane(fondo);
        initComponents();
        setLocationRelativeTo(null);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/Imagenes/tambo-3.jpg"));
        Image image = icon.getImage();
        escritorio = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        opClientes = new javax.swing.JMenuItem();
        opProductos = new javax.swing.JMenuItem();
        opProveedor = new javax.swing.JMenuItem();
        opCategoria = new javax.swing.JMenuItem();
        opUsuarios = new javax.swing.JMenuItem();
        opRol = new javax.swing.JMenuItem();
        opTiendas = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        escritorio.setPreferredSize(new java.awt.Dimension(900, 550));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        jMenu1.setText("Mantenedor");

        opClientes.setText("Clientes");
        opClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opClientesActionPerformed(evt);
            }
        });
        jMenu1.add(opClientes);

        opProductos.setText("Productos");
        opProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opProductosActionPerformed(evt);
            }
        });
        jMenu1.add(opProductos);

        opProveedor.setText("Proveedor");
        opProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opProveedorActionPerformed(evt);
            }
        });
        jMenu1.add(opProveedor);

        opCategoria.setText("Categoria");
        opCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opCategoriaActionPerformed(evt);
            }
        });
        jMenu1.add(opCategoria);

        opUsuarios.setText("Usuarios");
        opUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opUsuariosActionPerformed(evt);
            }
        });
        jMenu1.add(opUsuarios);

        opRol.setText("Rol");
        opRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opRolActionPerformed(evt);
            }
        });
        jMenu1.add(opRol);

        opTiendas.setText("Tiendas");
        opTiendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opTiendasActionPerformed(evt);
            }
        });
        jMenu1.add(opTiendas);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ventas");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Compras");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Reporte");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Salir");
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opClientesActionPerformed

        ClientesMantenedor Clientes1=new ClientesMantenedor ();
        escritorio.add(Clientes1);
        Clientes1.show();

        // TODO add your handling code here:
    }//GEN-LAST:event_opClientesActionPerformed

    private void opProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opProductosActionPerformed

        ProductosMantenedor Productos1=new ProductosMantenedor();
        escritorio.add(Productos1);
        Productos1.show();
    }//GEN-LAST:event_opProductosActionPerformed

    private void opCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opCategoriaActionPerformed

        CategoriaMantenedor Categoria1=new CategoriaMantenedor();
        escritorio.add(Categoria1);
        Categoria1.show();     // TODO add your handling code here:
    }//GEN-LAST:event_opCategoriaActionPerformed

    private void opUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opUsuariosActionPerformed

        UsuariosMantenedor Usuarios1=new UsuariosMantenedor();
        escritorio.add(Usuarios1);
        Usuarios1.show();       // TODO add your handling code here:
    }//GEN-LAST:event_opUsuariosActionPerformed

    private void opRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opRolActionPerformed

        RolMantenedor Rol1=new RolMantenedor();
        escritorio.add(Rol1);
        Rol1.show();      // TODO add your handling code here:
    }//GEN-LAST:event_opRolActionPerformed

    private void opTiendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opTiendasActionPerformed

        TiendasMantenedor Tiendas1=new TiendasMantenedor();
        escritorio.add(Tiendas1);
        Tiendas1.show();
               // TODO add your handling code here:
    }//GEN-LAST:event_opTiendasActionPerformed

    private void opProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opProveedorActionPerformed

        ProveedorMantenedor Proveedor1=new ProveedorMantenedor();
        escritorio.add(Proveedor1);
        Proveedor1.show();
    }//GEN-LAST:event_opProveedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mantenedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mantenedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mantenedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mantenedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mantenedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem opCategoria;
    private javax.swing.JMenuItem opClientes;
    private javax.swing.JMenuItem opProductos;
    private javax.swing.JMenuItem opProveedor;
    private javax.swing.JMenuItem opRol;
    private javax.swing.JMenuItem opTiendas;
    private javax.swing.JMenuItem opUsuarios;
    // End of variables declaration//GEN-END:variables

class FondoPanel extends JPanel
    {
        private Image imagen;
        
        @Override
        public void paint(Graphics g)
        {
            imagen = new ImageIcon(getClass().getResource("/Imagenes/tambo-3.jpg")).getImage();
            
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            
            super.paint(g);
}
}
}
